
spring:
  profiles:
    active:
      - 7001

---
server:
  port: 7001
spring:
  application:
    name: eureka_server_7001
  profiles:
    active: 7001
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka.com:7002/eureka/,http://eureka.com:7003/eureka/
      
---
server:
  port: 7002
spring:
  application:
    name: eureka_server_7002
  profiles:
    active: 7002
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka.com:7001/eureka/,http://eureka.com:7003/eureka/
      
---
server:
  port: 7003
spring:
  application:
    name: eureka_server_7003
  profiles:
    active: 7003
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka.com:7002/eureka/,http://eureka.com:7001/eureka/
