spring:
  profiles:
    active:
    - dev
---
server: 
  port: 3355
spring:
  profiles: dev
  application: 
    name: microservicecloud-config-client1
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/   
---
server: 
  port: 3355
spring:
  profiles: test
  application: 
    name: microservicecloud-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
 

